development:
  adapter: postgresql
  encoding: unicode
  database: rangerapp
  pool: 5
  host: localhost
  username: ranger
  password: ranger6y6y

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: ranger
  password: ranger6y6y